version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel-task-manager
        container_name: laravel_task_app
        restart: unless-stopped
        volumes:
            - .:/var/www
        ports:
            - 9001:9000
        depends_on:
            - db
        networks:
            - laravel
        environment:
            DB_CONNECTION: pgsql
            DB_HOST: ${DB_HOST}
            DB_PORT: 5432
            DB_DATABASE: ${DB_DATABASE}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}

    webserver:
        image: nginx:alpine
        container_name: laravel_nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - .:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel

    db:
        image: postgres:15
        container_name: laravel_postgres
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - "5433:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - laravel

volumes:
    pgdata:

networks:
    laravel:
